<!DOCTYPEhtml >
< html >
	< meta  charset =" UTF-8 " >
	< corpo >
		< h2 > Signos </ h2 >
		< form  ação =" signo.php " >
			< label  for =" nome " > Nome: </ label > < br >
			< tipo de entrada  =" texto " nome =" nome " obrigatório > < br >
			< label  for =" nascimento " > Nascimento: </ label > < br >
			< tipo de entrada  =" data " nome =" nascimento " obrigatório > < br > < br >
			< tipo de entrada  =" enviar " valor =" Ok " >
		</ formulário > 
		< p > Preencha os dados e veja oque seu horóscopo tem a dizer sobre você. </ p >
	</ corpo >
</ html >
